[project]
name = "primomaps"
version = "0.1.0"
description = ""
readme = "../README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.2",
]

[dependency-groups]
dev = [
    "httpx2>=2.12.0",
    "mypy>=2.3.1",
    "pip-audit>=2.10.1",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.4",
]

[tool.mypy]
ignore_missing_imports = true

[tool.pytest.ini_options]
pythonpath = ["."]
